name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        
      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
